### ISSUE TITLE
Support download API calls

### ISSUE THREAD

**Issue by SaraVieira** [axodotdev/octolotl#1]
In oranda we use this to fetch the releases, but it would be great if we could also use it to get the files.

Currently, the API does not support the URL needed for this:

```
https://github.com/axodotdev/oranda/releases/download/v0.0.1/dist-manifest.json
```

If I am shown how to test this locally I can definitely add support for the download route at:

```
https://octolotl.axodotdev.host/releases/download/axodotdev/oranda/v0.0.1/dist-manifest.json
```

**Comment by ashleygwilliams** [comment]
this functionality exists now!
